/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import java.io.File;
import static java.lang.String.format;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mr.W
 */
public class TelaPrincipal extends javax.swing.JFrame {

	public String username;

	public void recebeNome(String recebe) {
		username = recebe;
	}

	public TelaPrincipal() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		painelTopo = new javax.swing.JPanel();
		painelLateral = new javax.swing.JPanel();
		btnMeuArmazenamento = new javax.swing.JButton();
		btnCompartilhados = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jProgressBar1 = new javax.swing.JProgressBar();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tabelaArquivos = new javax.swing.JTable();
		btnUpload = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("4 Storage - Meu Armazenamento");
		setPreferredSize(new java.awt.Dimension(800, 550));

		painelTopo.setPreferredSize(new java.awt.Dimension(890, 120));

		javax.swing.GroupLayout painelTopoLayout = new javax.swing.GroupLayout(painelTopo);
		painelTopo.setLayout(painelTopoLayout);
		painelTopoLayout.setHorizontalGroup(painelTopoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));
		painelTopoLayout.setVerticalGroup(painelTopoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 120, Short.MAX_VALUE));

		painelLateral.setPreferredSize(new java.awt.Dimension(220, 100));

		btnMeuArmazenamento.setBackground(new java.awt.Color(51, 51, 51));
		btnMeuArmazenamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnMeuArmazenamento.setForeground(new java.awt.Color(255, 255, 255));
		btnMeuArmazenamento.setText("Meu Armazenamento");

		btnCompartilhados.setBackground(new java.awt.Color(51, 51, 51));
		btnCompartilhados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnCompartilhados.setForeground(new java.awt.Color(255, 255, 255));
		btnCompartilhados.setText("Compartilhados");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane4.setViewportView(jTextArea1);

		jButton1.setText("L");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("0 / 15gb");

		javax.swing.GroupLayout painelLateralLayout = new javax.swing.GroupLayout(painelLateral);
		painelLateral.setLayout(painelLateralLayout);
		painelLateralLayout.setHorizontalGroup(painelLateralLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(painelLateralLayout.createSequentialGroup().addGroup(painelLateralLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(painelLateralLayout.createSequentialGroup().addGap(81, 81, 81)
								.addGroup(painelLateralLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1).addComponent(jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(painelLateralLayout.createSequentialGroup().addContainerGap()
								.addGroup(painelLateralLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnMeuArmazenamento, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnCompartilhados, javax.swing.GroupLayout.DEFAULT_SIZE, 190,
												Short.MAX_VALUE)
										.addComponent(jScrollPane4))))
						.addContainerGap()));
		painelLateralLayout.setVerticalGroup(painelLateralLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(painelLateralLayout.createSequentialGroup()
						.addComponent(btnMeuArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnCompartilhados, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		jPanel1.setForeground(new java.awt.Color(255, 255, 255));

		tabelaArquivos.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "NOME DO ARQUIVO", "TAMANHO", "UPLOADER", "DATA" }));
		jScrollPane2.setViewportView(tabelaArquivos);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jScrollPane2,
						javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 29, Short.MAX_VALUE)));

		jScrollPane1.setViewportView(jPanel1);

		btnUpload.setBackground(new java.awt.Color(51, 51, 51));
		btnUpload.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnUpload.setForeground(new java.awt.Color(255, 255, 255));
		btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload.png"))); // NOI18N
		btnUpload.setText("Upload");
		btnUpload.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
		btnUpload.setMaximumSize(new java.awt.Dimension(71, 25));
		btnUpload.setMinimumSize(new java.awt.Dimension(71, 25));
		btnUpload.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUploadActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash1.png"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(painelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 210,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(10, 10, 10)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(117, 117, 117)
								.addComponent(painelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
						.addComponent(jScrollPane1))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(painelTopo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1).addComponent(painelLateral,
										javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
						.addGap(10, 10, 10)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUploadActionPerformed

		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setDialogTitle("Buscar Arquivo");
		fileChooser.setMultiSelectionEnabled(true);
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

		FileNameExtensionFilter filter = new FileNameExtensionFilter("Todos os arquivos", "jpg", "txt", "png", "pdf",
				"doc");

		fileChooser.setFileFilter(filter);
		fileChooser.addChoosableFileFilter(null);

		int retorno = fileChooser.showOpenDialog(this);

		if (retorno == JFileChooser.APPROVE_OPTION) { //
			File file = fileChooser.getSelectedFile();
			@SuppressWarnings("unused")
			File[] files = fileChooser.getSelectedFiles();
			DefaultTableModel dtm = (DefaultTableModel) tabelaArquivos.getModel();

			double tamanho = file.length() / 1048726D; // pega tamanho do arquivo em bytes
			String fmt = format("%.2f", tamanho);

			java.util.Date d = new Date();
			String data = java.text.DateFormat.getDateInstance(DateFormat.MEDIUM).format(d);

			Object[] dados = { file.getName(), fmt + "MB", username, data };
			dtm.addRow(dados);

		} // GEN-LAST:event_btnUploadActionPerformed

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaPrincipal().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCompartilhados;
	private javax.swing.JButton btnMeuArmazenamento;
	private javax.swing.JButton btnUpload;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JProgressBar jProgressBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JPanel painelLateral;
	private javax.swing.JPanel painelTopo;
	private javax.swing.JTable tabelaArquivos;
	// End of variables declaration//GEN-END:variables
}
